name: Match Racing!
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2767292186617851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a6c3f'
    - '#012350'
    - '#007cb2'
    - '#f9fefe'
    - '#8eb7c9'
  brandStrength: 0.4136274312622845
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
