name: Match Racing!
favicon: null
layout_spectrum: 0.6745062619447708
typography_spectrum: 0.2767292186617851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4136274312622845
  lightness: 0.6446488155052066
  saturation: 0.9380344552919269
  rhythmicContrast: 0.9314099743496627
purpose: []
